In [1]:
import pandas as pd
import numpy as np
import sklearn
import stat
import statsmodels.api as sm
import matplotlib.pyplot as plt
import matplotlib as mpl
import seaborn as sns

years = pd.read_csv("years.csv")
weeks = pd.read_csv("weeks.csv")
info = pd.read_csv("info.csv")
years.drop(columns = ['Unnamed: 0'], inplace=True)
weeks.drop(columns = ['Unnamed: 0'], inplace=True)

In [6]:
monthly_page = pd.read_csv("monthly_means.csv")
monthly_count = pd.read_csv("monthly_df_count.csv")

yearly_page = pd.read_csv("yearly_means.csv")
yearly_count = pd.read_csv("yearly_count.csv")

# monthly_page.drop(columns = ['Unnamed: 0'], inplace=True)
# monthly_count.drop(columns = ['Unnamed: 0'], inplace=True)
# yearly_page.drop(columns = ['Unnamed: 0'], inplace=True)
# yearly_count.drop(columns = ['Unnamed: 0'], inplace=True)

In [7]:
yearly_page

,Unnamed: 0,인문학,에세이,소설/시/희곡,경제경영,청소년,자기계발,종교/역학,외국어,사회과학,...,역사,건강/취미,요리/살림,과학,성인물,고전,만화,여행,컴퓨터/모바일,대학교재/전문서적
0,2010,411.400000,373.159091,384.101266,355.652174,282.066667,295.775000,305.318182,435.750000,382.153846,...,320.000000,201.833333,231.750000,417.600000,NaN,NaN,NaN,NaN,NaN,NaN
1,2011,378.777778,349.294118,375.526316,373.823529,276.411765,301.658537,285.294118,450.055556,275.466667,...,384.000000,158.500000,274.285714,294.333333,NaN,233.0,320.000000,NaN,NaN,NaN
2,2012,422.920000,319.080000,460.590909,373.411765,391.800000,320.031250,265.500000,483.304348,309.076923,...,425.600000,272.000000,267.833333,448.600000,NaN,233.0,196.000000,NaN,NaN,NaN
3,2013,418.500000,311.192308,424.588785,325.555556,370.857143,316.419355,286.666667,445.695652,282.500000,...,2297.333333,144.000000,308.111111,548.000000,NaN,233.0,324.333333,396.0,NaN,NaN
4,2014,451.885714,287.041667,431.618644,368.000000,286.500000,306.333333,294.000000,414.740741,377.000000,...,1282.833333,132.000000,326.777778,568.500000,NaN,233.0,452.500000,380.0,NaN,NaN
5,2015,392.724138,308.909091,408.477064,351.600000,268.000000,293.187500,428.000000,436.866667,289.923077,...,361.333333,80.666667,313.750000,546.142857,NaN,233.0,328.222222,624.0,620.000000,NaN
6,2016,354.558824,304.628571,358.512397,359.636364,304.000000,306.333333,280.000000,503.088235,338.750000,...,927.300000,195.000000,273.000000,566.111111,NaN,233.0,206.142857,566.0,620.000000,NaN
7,2017,380.882353,278.375000,347.891892,377.541667,296.000000,309.863636,280.000000,472.155556,283.333333,...,966.900000,240.000000,344.000000,503.375000,NaN,233.0,340.666667,566.0,620.000000,NaN
8,2018,364.184211,303.674419,342.892857,375.043478,236.000000,323.176471,280.000000,412.115385,428.000000,...,445.333333,315.200000,354.000000,471.100000,NaN,233.0,670.700000,566.0,367.333333,NaN
9,2019,434.681818,305.000000,350.526882,352.000000,200.000000,315.142857,280.000000,422.843750,315.750000,...,431.428571,396.000000,228.666667,469.545455,NaN,233.0,286.736842,566.0,404.000000,NaN
10,2020,431.000000,265.259259,329.453333,402.196078,267.250000,303.900000,280.000000,454.350000,357.466667,...,422.400000,248.400000,226.000000,499.545455,NaN,233.0,249.555556,566.0,506.000000,NaN
11,2021,382.714286,274.880000,529.358209,364.315789,216.000000,312.857143,280.000000,469.857143,381.333333,...,383.000000,484.000000,226.000000,523.900000,NaN,233.0,211.823529,566.0,506.000000,408.0
12,2022,337.200000,284.000000,325.276923,397.111111,276.666667,321.880000,320.000000,455.550000,340.888889,...,403.000000,419.000000,204.000000,513.375000,NaN,233.0,199.375000,566.0,534.000000,408.0
13,2023,427.440000,273.304348,306.378788,411.948718,290.666667,362.151515,412.000000,494.080000,354.666667,...,350.000000,381.125000,144.000000,529.727273,NaN,233.0,236.129630,566.0,725.000000,408.0

In [8]:
import sklearn
from sklearn import linear_model

In [12]:
lm = linear_model.LinearRegression()

In [14]:
lm.fit(yearly_page[['Unnamed: 0']], yearly_page[['인문학']])

LinearRegression()

In [15]:
lm.coef_

array([[-1.46923674]])

In [18]:
lm.score(yearly_page[['Unnamed: 0']], yearly_page[['인문학']])

0.03261631668477949

In [19]:
monthly_page

,Unnamed: 0,year,month,건강/취미,경제경영,고전,과학,달력/기타,대학교재/전문서적,만화,...,인문학,자기계발,잡지,전집/중고전집,종교/역학,좋은부모,참고서,청소년,컴퓨터/모바일,해외잡지
0,0,2010,1,261.160000,320.546012,NaN,477.800000,NaN,NaN,209.875000,...,369.541176,304.830645,NaN,NaN,305.870968,365.988764,120.0,285.351064,317.000000,NaN
1,1,2010,2,223.387097,319.034783,NaN,424.703704,NaN,562.000000,198.034483,...,460.164706,290.414815,NaN,NaN,299.761905,359.279070,120.0,271.434211,337.200000,NaN
2,2,2010,3,145.666667,353.481481,NaN,608.000000,NaN,562.000000,220.000000,...,621.782609,279.645161,NaN,NaN,273.920000,409.121951,120.0,254.700000,343.000000,NaN
3,3,2010,4,210.292683,351.981132,NaN,451.000000,NaN,159.500000,192.760870,...,414.478723,292.175573,NaN,NaN,276.408451,340.723404,161.0,238.597015,304.000000,NaN
4,4,2010,5,232.145833,365.053030,271.0,478.457143,NaN,416.600000,186.423077,...,439.518519,294.411429,NaN,NaN,295.672727,352.827957,138.0,254.935484,236.833333,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175,175,2024,8,305.456522,356.115942,860.0,466.812500,26.0,855.942857,199.742160,...,355.239437,336.643564,104.0,30.0,627.766667,395.520000,1044.0,247.250000,425.933333,62.0
176,176,2024,9,282.314286,381.042017,860.0,437.462963,26.0,642.885714,206.853755,...,351.095436,318.440367,104.0,30.0,253.200000,411.520000,1044.0,250.301887,480.923077,62.0
177,177,2024,10,349.975610,364.705882,860.0,493.220588,26.0,386.000000,208.599034,...,359.947581,321.302521,104.0,30.0,387.520000,423.111111,1044.0,264.755556,422.400000,62.0
178,178,2024,11,296.222222,361.171429,860.0,470.450000,26.0,800.000000,219.810811,...,348.567797,327.016529,104.0,30.0,532.800000,393.333333,1044.0,250.465116,413.368421,62.0
179,179,2024,12,261.333333,370.935780,860.0,445.108108,26.0,800.000000,212.685714,...,361.140625,336.622222,104.0,30.0,491.500000,408.705882,1044.0,253.857143,514.285714,62.0

In [22]:
lm.fit(monthly_page[['Unnamed: 0']], monthly_page[['인문학']])

print(lm.coef_)
print(lm.score(monthly_page[['Unnamed: 0']], monthly_page[['인문학']]))

[[-0.27083981]]
0.170583722923782

In [23]:
df_regs = pd.DataFrame()

In [25]:
len(monthly_page.columns)

31

In [26]:
len(yearly_page.columns)

24

In [37]:
monthly_page2 = monthly_page.fillna(method='ffill')
yearly_page2 = yearly_page.fillna(method='ffill')

C:\Users\user\AppData\Local\Temp\ipykernel_30904\602055261.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  monthly_page2 = monthly_page.fillna(method='ffill')
C:\Users\user\AppData\Local\Temp\ipykernel_30904\602055261.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  yearly_page2 = yearly_page.fillna(method='ffill')

In [41]:
yearly_page

,Unnamed: 0,인문학,에세이,소설/시/희곡,경제경영,청소년,자기계발,종교/역학,외국어,사회과학,...,역사,건강/취미,요리/살림,과학,성인물,고전,만화,여행,컴퓨터/모바일,대학교재/전문서적
0,2010,411.400000,373.159091,384.101266,355.652174,282.066667,295.775000,305.318182,435.750000,382.153846,...,320.000000,201.833333,231.750000,417.600000,NaN,NaN,NaN,NaN,NaN,NaN
1,2011,378.777778,349.294118,375.526316,373.823529,276.411765,301.658537,285.294118,450.055556,275.466667,...,384.000000,158.500000,274.285714,294.333333,NaN,233.0,320.000000,NaN,NaN,NaN
2,2012,422.920000,319.080000,460.590909,373.411765,391.800000,320.031250,265.500000,483.304348,309.076923,...,425.600000,272.000000,267.833333,448.600000,NaN,233.0,196.000000,NaN,NaN,NaN
3,2013,418.500000,311.192308,424.588785,325.555556,370.857143,316.419355,286.666667,445.695652,282.500000,...,2297.333333,144.000000,308.111111,548.000000,NaN,233.0,324.333333,396.0,NaN,NaN
4,2014,451.885714,287.041667,431.618644,368.000000,286.500000,306.333333,294.000000,414.740741,377.000000,...,1282.833333,132.000000,326.777778,568.500000,NaN,233.0,452.500000,380.0,NaN,NaN
5,2015,392.724138,308.909091,408.477064,351.600000,268.000000,293.187500,428.000000,436.866667,289.923077,...,361.333333,80.666667,313.750000,546.142857,NaN,233.0,328.222222,624.0,620.000000,NaN
6,2016,354.558824,304.628571,358.512397,359.636364,304.000000,306.333333,280.000000,503.088235,338.750000,...,927.300000,195.000000,273.000000,566.111111,NaN,233.0,206.142857,566.0,620.000000,NaN
7,2017,380.882353,278.375000,347.891892,377.541667,296.000000,309.863636,280.000000,472.155556,283.333333,...,966.900000,240.000000,344.000000,503.375000,NaN,233.0,340.666667,566.0,620.000000,NaN
8,2018,364.184211,303.674419,342.892857,375.043478,236.000000,323.176471,280.000000,412.115385,428.000000,...,445.333333,315.200000,354.000000,471.100000,NaN,233.0,670.700000,566.0,367.333333,NaN
9,2019,434.681818,305.000000,350.526882,352.000000,200.000000,315.142857,280.000000,422.843750,315.750000,...,431.428571,396.000000,228.666667,469.545455,NaN,233.0,286.736842,566.0,404.000000,NaN
10,2020,431.000000,265.259259,329.453333,402.196078,267.250000,303.900000,280.000000,454.350000,357.466667,...,422.400000,248.400000,226.000000,499.545455,NaN,233.0,249.555556,566.0,506.000000,NaN
11,2021,382.714286,274.880000,529.358209,364.315789,216.000000,312.857143,280.000000,469.857143,381.333333,...,383.000000,484.000000,226.000000,523.900000,NaN,233.0,211.823529,566.0,506.000000,408.0
12,2022,337.200000,284.000000,325.276923,397.111111,276.666667,321.880000,320.000000,455.550000,340.888889,...,403.000000,419.000000,204.000000,513.375000,NaN,233.0,199.375000,566.0,534.000000,408.0
13,2023,427.440000,273.304348,306.378788,411.948718,290.666667,362.151515,412.000000,494.080000,354.666667,...,350.000000,381.125000,144.000000,529.727273,NaN,233.0,236.129630,566.0,725.000000,408.0

In [45]:
lm.fit(yearly_page2[['Unnamed: 0']], yearly_page2[['인문학']])
lm.coef_[0][0]
# lm.score(yearly_page2[['Unnamed: 0']], yearly_page2[['인문학']])

-1.469236741645837

In [50]:
df_regs = pd.DataFrame(columns = ['month_coef', 'month_score', 'year_coef', 'year_score'])
for i in monthly_page.columns[3:]:
    
    try:
        lm.fit(monthly_page2[['Unnamed: 0']], monthly_page2[[i]])
    
        df_regs.loc[i, 'month_coef'] = lm.coef_[0][0]
        df_regs.loc[i, 'month_score'] = lm.score(monthly_page2[['Unnamed: 0']], monthly_page2[[i]])
    except:
        print(f"{i}: NaN")
        continue

    try:
        lm.fit(yearly_page2[['Unnamed: 0']], yearly_page2[[i]])
        df_reg.loc[i, 'year_coef'] = lm.coef_[0][0]
        df_reg.loc[i, 'year_score'] = lm.score(yearly_page2[['Unnamed: 0']], yearly_page2[[i]])
    except:
        print(f"{i}: NaN2")
        pass

    j += 1

건강/취미: NaN2
경제경영: NaN2
고전: NaN
과학: NaN2
달력/기타: NaN
대학교재/전문서적: NaN
만화: NaN2
사회과학: NaN2
소설/시/희곡: NaN2
수험서/자격증: NaN2
어린이: NaN
에세이: NaN2
여행: NaN2
역사: NaN2
예술/대중문화: NaN2
외국어: NaN2
요리/살림: NaN2
유아: NaN
인문학: NaN2
자기계발: NaN2
잡지: NaN
전집/중고전집: NaN
종교/역학: NaN2
좋은부모: NaN2
참고서: NaN2
청소년: NaN2
컴퓨터/모바일: NaN2
해외잡지: NaN

In [54]:
df_regs = pd.DataFrame(columns=['month_coef', 'month_score', 'year_coef', 'year_score'])

for i in monthly_page.columns[3:]:
    try:
        lm.fit(monthly_page2[['Unnamed: 0']], monthly_page2[[i]])
        df_regs.loc[i, 'month_coef'] = lm.coef_[0]
        df_regs.loc[i, 'month_score'] = lm.score(monthly_page2[['Unnamed: 0']], monthly_page2[[i]])
    except Exception as e:
        print(f"{i}: Month Error: {e}")
        continue

    try:
        lm.fit(yearly_page2[['Unnamed: 0']], yearly_page2[[i]])
        df_regs.loc[i, 'year_coef'] = lm.coef_[0]
        df_regs.loc[i, 'year_score'] = lm.score(yearly_page2[['Unnamed: 0']], yearly_page2[[i]])
    except Exception as e:
        print(f"{i}2: Year Error: {e} 2")

고전: Month Error: Input y contains NaN.
달력/기타: Month Error: Input y contains NaN.
대학교재/전문서적: Month Error: Input y contains NaN.
만화2: Year Error: Input y contains NaN. 2
수험서/자격증2: Year Error: "None of [Index(['수험서/자격증'], dtype='object')] are in the [columns]" 2
어린이: Month Error: Input y contains NaN.
여행2: Year Error: Input y contains NaN. 2
유아: Month Error: Input y contains NaN.
잡지: Month Error: Input y contains NaN.
전집/중고전집: Month Error: Input y contains NaN.
참고서2: Year Error: "None of [Index(['참고서'], dtype='object')] are in the [columns]" 2
컴퓨터/모바일2: Year Error: Input y contains NaN. 2
해외잡지: Month Error: Input y contains NaN.

In [55]:
df_regs = pd.DataFrame(columns=['month_coef', 'month_score', 'year_coef', 'year_score'])

for i in monthly_page2.columns[3:]:
    try:
        if monthly_page2[i].isna().any():
            raise ValueError(f"NaN detected in monthly_page2[{i}]")
        
        lm.fit(monthly_page2[['Unnamed: 0']], monthly_page2[[i]])
        df_regs.loc[i, 'month_coef'] = lm.coef_[0]
        df_regs.loc[i, 'month_score'] = lm.score(monthly_page2[['Unnamed: 0']], monthly_page2[[i]])
    except Exception as e:
        print(f"{i}: Month Error: {e}")
        continue

    try:
        if i not in yearly_page2.columns:
            raise KeyError(f"{i} not found in yearly_page2")
        if yearly_page2[i].isna().any():
            raise ValueError(f"NaN detected in yearly_page2[{i}]")
        
        lm.fit(yearly_page2[['Unnamed: 0']], yearly_page2[[i]])
        df_regs.loc[i, 'year_coef'] = lm.coef_[0]
        df_regs.loc[i, 'year_score'] = lm.score(yearly_page2[['Unnamed: 0']], yearly_page2[[i]])
    except Exception as e:
        print(f"{i}: Year Error: {e}")

고전: Month Error: NaN detected in monthly_page2[고전]
달력/기타: Month Error: NaN detected in monthly_page2[달력/기타]
대학교재/전문서적: Month Error: NaN detected in monthly_page2[대학교재/전문서적]
만화: Year Error: NaN detected in yearly_page2[만화]
수험서/자격증: Year Error: '수험서/자격증 not found in yearly_page2'
어린이: Month Error: NaN detected in monthly_page2[어린이]
여행: Year Error: NaN detected in yearly_page2[여행]
유아: Month Error: NaN detected in monthly_page2[유아]
잡지: Month Error: NaN detected in monthly_page2[잡지]
전집/중고전집: Month Error: NaN detected in monthly_page2[전집/중고전집]
참고서: Year Error: '참고서 not found in yearly_page2'
컴퓨터/모바일: Year Error: NaN detected in yearly_page2[컴퓨터/모바일]
해외잡지: Month Error: NaN detected in monthly_page2[해외잡지]

In [56]:
df_regs

                   month_coef month_score           year_coef year_score
건강/취미       0.628172513892964    0.248938  21.766355311355312   0.560771
경제경영      0.05271276954436204    0.009524   3.188734268154782   0.349276
과학        0.17708820471073455    0.054368   7.523062968777255   0.189576
만화       -0.19683175645627263    0.047605                 NaN        NaN
사회과학      0.29067525405711586    0.128428  3.4943946651638993    0.10022
소설/시/희곡   -0.2151553155005203    0.117118    -4.8857361188925   0.111296
수험서/자격증   0.03479274676429431    0.000244                 NaN        NaN
에세이        -0.267446964431475    0.347183   -5.90734992286431   0.675611
여행        -1.0218484685891327    0.149819                 NaN        NaN
역사        -0.6925508368332064    0.036063  -37.08649921507064   0.078973
예술/대중문화    0.2986619385868786      0.0555   14.85897435897436   0.298427
외국어       0.23014360305252313    0.108011  1.5244241744063483   0.050671
요리/살림     -0.0315376830897123    0.001361  -6.953793825222395    0.23816
인문학       -0.2708398127452208    0.170584  -1.469236741645837   0.032616
자기계발      0.21394582044906055    0.386374   2.353127868607952   0.344164
종교/역학      0.5498044529905975    0.064935  2.9416740122622462   0.059737
좋은부모     -0.11851305376047216    0.033774  -4.649982430842159   0.148228
참고서        4.1864320243334365    0.528872                 NaN        NaN
청소년       -0.3199368163606592    0.020325  -5.998562809739279   0.238093
컴퓨터/모바일    0.8535386449441219    0.095059                 NaN        NaN

In [57]:
df_regs_count = pd.DataFrame(columns=['month_coef', 'month_score', 'year_coef', 'year_score'])

for i in monthly_count.columns[3:]:
    try:
        if monthly_count[i].isna().any():
            raise ValueError(f"NaN detected in monthly_count[{i}]")
        
        lm.fit(monthly_count[['Unnamed: 0']], monthly_count[[i]])
        df_regs_count.loc[i, 'month_coef'] = lm.coef_[0]
        df_regs_count.loc[i, 'month_score'] = lm.score(monthly_count[['Unnamed: 0']], monthly_count[[i]])
    except Exception as e:
        print(f"{i}: Month Error: {e}")
        continue

    try:
        if i not in yearly_count.columns:
            raise KeyError(f"{i} not found in yearly_count")
        if yearly_count[i].isna().any():
            raise ValueError(f"NaN detected in yearly_count[{i}]")
        
        lm.fit(yearly_count[['Unnamed: 0']], yearly_count[[i]])
        df_regs_count.loc[i, 'year_coef'] = lm.coef_[0]
        df_regs_count.loc[i, 'year_score'] = lm.score(yearly_count[['Unnamed: 0']], yearly_count[[i]])
    except Exception as e:
        print(f"{i}: Year Error: {e}")

고전: Month Error: NaN detected in monthly_count[고전]
달력/기타: Month Error: NaN detected in monthly_count[달력/기타]
대학교재/전문서적: Month Error: NaN detected in monthly_count[대학교재/전문서적]
수험서/자격증: Month Error: NaN detected in monthly_count[수험서/자격증]
어린이: Month Error: NaN detected in monthly_count[어린이]
여행: Month Error: NaN detected in monthly_count[여행]
역사: Month Error: NaN detected in monthly_count[역사]
유아: Month Error: NaN detected in monthly_count[유아]
잡지: Month Error: NaN detected in monthly_count[잡지]
전집/중고전집: Month Error: NaN detected in monthly_count[전집/중고전집]
종교/역학: Month Error: NaN detected in monthly_count[종교/역학]
참고서: Month Error: NaN detected in monthly_count[참고서]
컴퓨터/모바일: Month Error: NaN detected in monthly_count[컴퓨터/모바일]
해외잡지: Month Error: NaN detected in monthly_count[해외잡지]

In [58]:
df_regs_count

                   month_coef month_score             year_coef year_score
건강/취미     0.06097204646233939    0.066558   0.02197802197802198    0.00221
경제경영        0.965967056596397    0.381824    2.8285714285714287   0.535743
과학        0.29787647766906383    0.593774   0.48791208791208796   0.520752
만화         1.3480138275872715    0.593831    3.9274725274725277   0.596969
사회과학     -0.14027079025072792    0.101398  -0.33406593406593404   0.092661
성인물      0.019211498297272547    0.001883   0.10769230769230768    0.17342
소설/시/희곡  -0.38619607601057654    0.033061   -0.9274725274725275   0.027735
에세이      -0.09028365072996081    0.016531   -0.9164835164835164   0.217834
예술/대중문화    0.1898885768079262    0.370501   0.43076923076923074   0.387805
외국어       0.18540284165149132    0.065016   0.03516483516483508    0.00023
요리/살림     -0.1923711637190449    0.285456   -0.5296703296703296    0.55397
인문학        0.4106916880150622    0.228927    0.5384615384615384   0.057043
자기계발     -0.09775816126012123    0.013906   -1.3472527472527471   0.295964
좋은부모      -0.2475343889214688    0.260349   -0.9868131868131869   0.630782
청소년      -0.20139510478718484    0.147479    -0.734065934065934   0.324801

In [59]:
import statsmodels.api as sm
import pandas as pd


df_regs_count = pd.DataFrame(columns=['month_coef', 'month_score', 'month_pvalue', 'year_coef', 'year_score', 'year_pvalue'])


lm = sm.OLS

for i in monthly_count.columns[3:]:
    try:
        if monthly_count[i].isna().any():
            raise ValueError(f"NaN detected in monthly_count[{i}]")
        
        X_month = sm.add_constant(monthly_count[['Unnamed: 0']])  
        y_month = monthly_count[i]
        model_month = lm(y_month, X_month).fit()
        
        df_regs_count.loc[i, 'month_coef'] = model_month.params[1] 
        df_regs_count.loc[i, 'month_score'] = model_month.rsquared  
        df_regs_count.loc[i, 'month_pvalue'] = model_month.pvalues[1] 

    except Exception as e:
        print(f"{i}: Month Error: {e}")
        continue

    try:
        if i not in yearly_count.columns:
            raise KeyError(f"{i} not found in yearly_count")
        if yearly_count[i].isna().any():
            raise ValueError(f"NaN detected in yearly_count[{i}]")
        
        X_year = sm.add_constant(yearly_count[['Unnamed: 0']])  
        y_year = yearly_count[i]
        model_year = lm(y_year, X_year).fit()

        df_regs_count.loc[i, 'year_coef'] = model_year.params[1]  
        df_regs_count.loc[i, 'year_score'] = model_year.rsquared  
        df_regs_count.loc[i, 'year_pvalue'] = model_year.pvalues[1]  

    except Exception as e:
        print(f"{i}: Year Error: {e}")
        continue

고전: Month Error: NaN detected in monthly_count[고전]
달력/기타: Month Error: NaN detected in monthly_count[달력/기타]
대학교재/전문서적: Month Error: NaN detected in monthly_count[대학교재/전문서적]
수험서/자격증: Month Error: NaN detected in monthly_count[수험서/자격증]
어린이: Month Error: NaN detected in monthly_count[어린이]
여행: Month Error: NaN detected in monthly_count[여행]
역사: Month Error: NaN detected in monthly_count[역사]
유아: Month Error: NaN detected in monthly_count[유아]
잡지: Month Error: NaN detected in monthly_count[잡지]
전집/중고전집: Month Error: NaN detected in monthly_count[전집/중고전집]
종교/역학: Month Error: NaN detected in monthly_count[종교/역학]
참고서: Month Error: NaN detected in monthly_count[참고서]
컴퓨터/모바일: Month Error: NaN detected in monthly_count[컴퓨터/모바일]
해외잡지: Month Error: NaN detected in monthly_count[해외잡지]

C:\Users\user\AppData\Local\Temp\ipykernel_30904\466119528.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df_regs_count.loc[i, 'month_coef'] = model_month.params[1]
C:\Users\user\AppData\Local\Temp\ipykernel_30904\466119528.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df_regs_count.loc[i, 'month_pvalue'] = model_month.pvalues[1]
C:\Users\user\AppData\Local\Temp\ipykernel_30904\466119528.py:37: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df_regs_count.loc[i, 'year_coef'] = model_year.params[1]
C:\Users\user\AppData\Local\Temp\ipykernel_30904\466119528.py:39: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df_regs_count.loc[i, 'year_pvalue'] = model_year.pvalues[1]
C:\Users\user\AppData\Local\Temp\ipykernel_30904\466119528.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df_regs_count.loc[i, 'month_coef'] = model_month.params[1]
C:\Users\user\AppData\Local\Temp\ipykernel_30904\466119528.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df_regs_count.loc[i, 'month_pvalue'] = model_month.pvalues[1]
C:\Users\user\AppData\Local\Temp\ipykernel_30904\466119528.py:37: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df_regs_count.loc[i, 'year_coef'] = model_year.params[1]
C:\Users\user\AppData\Local\Temp\ipykernel_30904\466119528.py:39: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df_regs_count.loc[i, 'year_pvalue'] = model_year.pvalues[1]
C:\Users\user\AppData\Local\Temp\ipykernel_30904\466119528.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df_regs_count.loc[i, 'month_coef'] = model_month.params[1]
C:\Users\user\AppData\Local\Temp\ipykernel_30904\466119528.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df_regs_count.loc[i, 'month_pvalue'] = model_month.pvalues[1]
C:\Users\user\AppData\Local\Temp\ipykernel_30904\466119528.py:37: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df_regs_count.loc[i, 'year_coef'] = model_year.params[1]
C:\Users\user\AppData\Local\Temp\ipykernel_30904\466119528.py:39: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df_regs_count.loc[i, 'year_pvalue'] = model_year.pvalues[1]
C:\Users\user\AppData\Local\Temp\ipykernel_30904\466119528.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df_regs_count.loc[i, 'month_coef'] = model_month.params[1]
C:\Users\user\AppData\Local\Temp\ipykernel_30904\466119528.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df_regs_count.loc[i, 'month_pvalue'] = model_month.pvalues[1]
C:\Users\user\AppData\Local\Temp\ipykernel_30904\466119528.py:37: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df_regs_count.loc[i, 'year_coef'] = model_year.params[1]
C:\Users\user\AppData\Local\Temp\ipykernel_30904\466119528.py:39: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df_regs_count.loc[i, 'year_pvalue'] = model_year.pvalues[1]
C:\Users\user\AppData\Local\Temp\ipykernel_30904\466119528.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df_regs_count.loc[i, 'month_coef'] = model_month.params[1]
C:\Users\user\AppData\Local\Temp\ipykernel_30904\466119528.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df_regs_count.loc[i, 'month_pvalue'] = model_month.pvalues[1]
C:\Users\user\AppData\Local\Temp\ipykernel_30904\466119528.py:37: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df_regs_count.loc[i, 'year_coef'] = model_year.params[1]
C:\Users\user\AppData\Local\Temp\ipykernel_30904\466119528.py:39: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df_regs_count.loc[i, 'year_pvalue'] = model_year.pvalues[1]
C:\Users\user\AppData\Local\Temp\ipykernel_30904\466119528.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df_regs_count.loc[i, 'month_coef'] = model_month.params[1]
C:\Users\user\AppData\Local\Temp\ipykernel_30904\466119528.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df_regs_count.loc[i, 'month_pvalue'] = model_month.pvalues[1]
C:\Users\user\AppData\Local\Temp\ipykernel_30904\466119528.py:37: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df_regs_count.loc[i, 'year_coef'] = model_year.params[1]
C:\Users\user\AppData\Local\Temp\ipykernel_30904\466119528.py:39: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df_regs_count.loc[i, 'year_pvalue'] = model_year.pvalues[1]
C:\Users\user\AppData\Local\Temp\ipykernel_30904\466119528.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df_regs_count.loc[i, 'month_coef'] = model_month.params[1]
C:\Users\user\AppData\Local\Temp\ipykernel_30904\466119528.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df_regs_count.loc[i, 'month_pvalue'] = model_month.pvalues[1]
C:\Users\user\AppData\Local\Temp\ipykernel_30904\466119528.py:37: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df_regs_count.loc[i, 'year_coef'] = model_year.params[1]
C:\Users\user\AppData\Local\Temp\ipykernel_30904\466119528.py:39: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df_regs_count.loc[i, 'year_pvalue'] = model_year.pvalues[1]
C:\Users\user\AppData\Local\Temp\ipykernel_30904\466119528.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df_regs_count.loc[i, 'month_coef'] = model_month.params[1]
C:\Users\user\AppData\Local\Temp\ipykernel_30904\466119528.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df_regs_count.loc[i, 'month_pvalue'] = model_month.pvalues[1]
C:\Users\user\AppData\Local\Temp\ipykernel_30904\466119528.py:37: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df_regs_count.loc[i, 'year_coef'] = model_year.params[1]
C:\Users\user\AppData\Local\Temp\ipykernel_30904\466119528.py:39: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df_regs_count.loc[i, 'year_pvalue'] = model_year.pvalues[1]
C:\Users\user\AppData\Local\Temp\ipykernel_30904\466119528.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df_regs_count.loc[i, 'month_coef'] = model_month.params[1]
C:\Users\user\AppData\Local\Temp\ipykernel_30904\466119528.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df_regs_count.loc[i, 'month_pvalue'] = model_month.pvalues[1]
C:\Users\user\AppData\Local\Temp\ipykernel_30904\466119528.py:37: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df_regs_count.loc[i, 'year_coef'] = model_year.params[1]
C:\Users\user\AppData\Local\Temp\ipykernel_30904\466119528.py:39: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df_regs_count.loc[i, 'year_pvalue'] = model_year.pvalues[1]
C:\Users\user\AppData\Local\Temp\ipykernel_30904\466119528.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df_regs_count.loc[i, 'month_coef'] = model_month.params[1]
C:\Users\user\AppData\Local\Temp\ipykernel_30904\466119528.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df_regs_count.loc[i, 'month_pvalue'] = model_month.pvalues[1]
C:\Users\user\AppData\Local\Temp\ipykernel_30904\466119528.py:37: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df_regs_count.loc[i, 'year_coef'] = model_year.params[1]
C:\Users\user\AppData\Local\Temp\ipykernel_30904\466119528.py:39: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df_regs_count.loc[i, 'year_pvalue'] = model_year.pvalues[1]
C:\Users\user\AppData\Local\Temp\ipykernel_30904\466119528.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df_regs_count.loc[i, 'month_coef'] = model_month.params[1]
C:\Users\user\AppData\Local\Temp\ipykernel_30904\466119528.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df_regs_count.loc[i, 'month_pvalue'] = model_month.pvalues[1]
C:\Users\user\AppData\Local\Temp\ipykernel_30904\466119528.py:37: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df_regs_count.loc[i, 'year_coef'] = model_year.params[1]
C:\Users\user\AppData\Local\Temp\ipykernel_30904\466119528.py:39: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df_regs_count.loc[i, 'year_pvalue'] = model_year.pvalues[1]
C:\Users\user\AppData\Local\Temp\ipykernel_30904\466119528.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df_regs_count.loc[i, 'month_coef'] = model_month.params[1]
C:\Users\user\AppData\Local\Temp\ipykernel_30904\466119528.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df_regs_count.loc[i, 'month_pvalue'] = model_month.pvalues[1]
C:\Users\user\AppData\Local\Temp\ipykernel_30904\466119528.py:37: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df_regs_count.loc[i, 'year_coef'] = model_year.params[1]
C:\Users\user\AppData\Local\Temp\ipykernel_30904\466119528.py:39: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df_regs_count.loc[i, 'year_pvalue'] = model_year.pvalues[1]
C:\Users\user\AppData\Local\Temp\ipykernel_30904\466119528.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df_regs_count.loc[i, 'month_coef'] = model_month.params[1]
C:\Users\user\AppData\Local\Temp\ipykernel_30904\466119528.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df_regs_count.loc[i, 'month_pvalue'] = model_month.pvalues[1]
C:\Users\user\AppData\Local\Temp\ipykernel_30904\466119528.py:37: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df_regs_count.loc[i, 'year_coef'] = model_year.params[1]
C:\Users\user\AppData\Local\Temp\ipykernel_30904\466119528.py:39: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df_regs_count.loc[i, 'year_pvalue'] = model_year.pvalues[1]
C:\Users\user\AppData\Local\Temp\ipykernel_30904\466119528.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df_regs_count.loc[i, 'month_coef'] = model_month.params[1]
C:\Users\user\AppData\Local\Temp\ipykernel_30904\466119528.py:21: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df_regs_count.loc[i, 'month_pvalue'] = model_month.pvalues[1]
C:\Users\user\AppData\Local\Temp\ipykernel_30904\466119528.py:37: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df_regs_count.loc[i, 'year_coef'] = model_year.params[1]

In [74]:
df_regs_count

        month_coef month_score month_pvalue year_coef year_score year_pvalue
건강/취미     0.060972    0.066558     0.000471  0.021978    0.00221    0.873196
경제경영      0.965967    0.381824          0.0  2.828571   0.535743     0.00292
과학        0.297876    0.593774          0.0  0.487912   0.520752    0.003573
만화        1.348014    0.593831          0.0  3.927473   0.596969    0.001197
사회과학     -0.140271    0.101398     0.000013 -0.334066   0.092661    0.289985
성인물       0.019211    0.001883     0.563009  0.107692    0.17342    0.138563
소설/시/희곡  -0.386196    0.033061     0.014571 -0.927473   0.027735    0.569336
에세이      -0.090284    0.016531     0.085411 -0.916484   0.217834    0.092485
예술/대중문화   0.189889    0.370501          0.0  0.430769   0.387805    0.017372
외국어       0.185403    0.065016     0.000552  0.035165    0.00023    0.958924
요리/살림    -0.192371    0.285456          0.0  -0.52967    0.55397    0.002266
인문학       0.410692    0.228927          0.0  0.538462   0.057043    0.410891
자기계발     -0.097758    0.013906      0.11489 -1.347253   0.295964    0.044314
좋은부모     -0.247534    0.260349          0.0 -0.986813   0.630782    0.000692
청소년      -0.201395    0.147479          0.0 -0.734066   0.324801     0.03336

In [73]:
print(df_regs_count.head(15).to_markdown())

|               |   month_coef |   month_score |   month_pvalue |   year_coef |   year_score |   year_pvalue |
|:--------------|-------------:|--------------:|---------------:|------------:|-------------:|--------------:|
| 건강/취미     |    0.060972  |    0.0665582  |    0.000471317 |   0.021978  |  0.00221043  |   0.873196    |
| 경제경영      |    0.965967  |    0.381824   |    2.4567e-20  |   2.82857   |  0.535743    |   0.00292017  |
| 과학          |    0.297876  |    0.593774   |    1.16952e-36 |   0.487912  |  0.520752    |   0.00357313  |
| 만화          |    1.34801   |    0.593831   |    1.15489e-36 |   3.92747   |  0.596969    |   0.00119745  |
| 사회과학      |   -0.140271  |    0.101398   |    1.32238e-05 |  -0.334066  |  0.0926606   |   0.289985    |
| 성인물        |    0.0192115 |    0.00188285 |    0.563009    |   0.107692  |  0.17342     |   0.138563    |
| 소설/시/희곡  |   -0.386196  |    0.0330612  |    0.0145709   |  -0.927473  |  0.0277348   |   0.569336    |
| 에세이        |   -0.0902837 |    0.016531   |    0.0854111   |  -0.916484  |  0.217834    |   0.0924854   |
| 예술/대중문화 |    0.189889  |    0.370501   |    1.254e-19   |   0.430769  |  0.387805    |   0.0173722   |
| 외국어        |    0.185403  |    0.0650156  |    0.000551554 |   0.0351648 |  0.000230427 |   0.958924    |
| 요리/살림     |   -0.192371  |    0.285456   |    1.12485e-14 |  -0.52967   |  0.55397     |   0.00226628  |
| 인문학        |    0.410692  |    0.228927   |    1.09644e-11 |   0.538462  |  0.0570425   |   0.410891    |
| 자기계발      |   -0.0977582 |    0.0139059  |    0.11489     |  -1.34725   |  0.295964    |   0.0443144   |
| 좋은부모      |   -0.247534  |    0.260349   |    2.54182e-13 |  -0.986813  |  0.630782    |   0.000692337 |
| 청소년        |   -0.201395  |    0.147479   |    1.02693e-07 |  -0.734066  |  0.324801    |   0.0333596   |

In [62]:
df_regs = pd.DataFrame(columns=['month_coef', 'month_score', 'month_pvalue', 'year_coef', 'year_score', 'year_pvalue'])

lm = sm.OLS

for i in monthly_page2.columns[3:]:
    try:
        if monthly_page2[i].isna().any():
            raise ValueError(f"NaN detected in monthly_page2[{i}]")
        
        X_month = sm.add_constant(monthly_page2[['Unnamed: 0']])  
        y_month = monthly_page2[i]
        model_month = lm(y_month, X_month).fit()
        
        df_regs.loc[i, 'month_coef'] = model_month.params[1]  
        df_regs.loc[i, 'month_score'] = model_month.rsquared  
        df_regs.loc[i, 'month_pvalue'] = model_month.pvalues[1]  

    except Exception as e:
        print(f"{i}: Month Error: {e}")
        continue

    try:
        if i not in yearly_page2.columns:
            raise KeyError(f"{i} not found in yearly_page2")
        if yearly_page2[i].isna().any():
            raise ValueError(f"NaN detected in yearly_page2[{i}]")
        
        X_year = sm.add_constant(yearly_page2[['Unnamed: 0']])  
        y_year = yearly_page2[i]
        model_year = lm(y_year, X_year).fit()

        df_regs.loc[i, 'year_coef'] = model_year.params[1] 
        df_regs.loc[i, 'year_score'] = model_year.rsquared  
        df_regs.loc[i, 'year_pvalue'] = model_year.pvalues[1] 

    except Exception as e:
        print(f"{i}: Year Error: {e}")
        continue

고전: Month Error: NaN detected in monthly_page2[고전]
달력/기타: Month Error: NaN detected in monthly_page2[달력/기타]
대학교재/전문서적: Month Error: NaN detected in monthly_page2[대학교재/전문서적]
만화: Year Error: NaN detected in yearly_page2[만화]
수험서/자격증: Year Error: '수험서/자격증 not found in yearly_page2'
어린이: Month Error: NaN detected in monthly_page2[어린이]
여행: Year Error: NaN detected in yearly_page2[여행]
유아: Month Error: NaN detected in monthly_page2[유아]
잡지: Month Error: NaN detected in monthly_page2[잡지]
전집/중고전집: Month Error: NaN detected in monthly_page2[전집/중고전집]
참고서: Year Error: '참고서 not found in yearly_page2'
컴퓨터/모바일: Year Error: NaN detected in yearly_page2[컴퓨터/모바일]
해외잡지: Month Error: NaN detected in monthly_page2[해외잡지]

C:\Users\user\AppData\Local\Temp\ipykernel_30904\3375503826.py:14: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df_regs.loc[i, 'month_coef'] = model_month.params[1]
C:\Users\user\AppData\Local\Temp\ipykernel_30904\3375503826.py:16: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df_regs.loc[i, 'month_pvalue'] = model_month.pvalues[1]
C:\Users\user\AppData\Local\Temp\ipykernel_30904\3375503826.py:32: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df_regs.loc[i, 'year_coef'] = model_year.params[1]
C:\Users\user\AppData\Local\Temp\ipykernel_30904\3375503826.py:34: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df_regs.loc[i, 'year_pvalue'] = model_year.pvalues[1]
C:\Users\user\AppData\Local\Temp\ipykernel_30904\3375503826.py:14: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df_regs.loc[i, 'month_coef'] = model_month.params[1]
C:\Users\user\AppData\Local\Temp\ipykernel_30904\3375503826.py:16: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df_regs.loc[i, 'month_pvalue'] = model_month.pvalues[1]
C:\Users\user\AppData\Local\Temp\ipykernel_30904\3375503826.py:32: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df_regs.loc[i, 'year_coef'] = model_year.params[1]
C:\Users\user\AppData\Local\Temp\ipykernel_30904\3375503826.py:34: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df_regs.loc[i, 'year_pvalue'] = model_year.pvalues[1]
C:\Users\user\AppData\Local\Temp\ipykernel_30904\3375503826.py:14: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df_regs.loc[i, 'month_coef'] = model_month.params[1]
C:\Users\user\AppData\Local\Temp\ipykernel_30904\3375503826.py:16: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df_regs.loc[i, 'month_pvalue'] = model_month.pvalues[1]
C:\Users\user\AppData\Local\Temp\ipykernel_30904\3375503826.py:32: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df_regs.loc[i, 'year_coef'] = model_year.params[1]
C:\Users\user\AppData\Local\Temp\ipykernel_30904\3375503826.py:34: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df_regs.loc[i, 'year_pvalue'] = model_year.pvalues[1]
C:\Users\user\AppData\Local\Temp\ipykernel_30904\3375503826.py:14: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df_regs.loc[i, 'month_coef'] = model_month.params[1]
C:\Users\user\AppData\Local\Temp\ipykernel_30904\3375503826.py:16: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df_regs.loc[i, 'month_pvalue'] = model_month.pvalues[1]
C:\Users\user\AppData\Local\Temp\ipykernel_30904\3375503826.py:14: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df_regs.loc[i, 'month_coef'] = model_month.params[1]
C:\Users\user\AppData\Local\Temp\ipykernel_30904\3375503826.py:16: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df_regs.loc[i, 'month_pvalue'] = model_month.pvalues[1]
C:\Users\user\AppData\Local\Temp\ipykernel_30904\3375503826.py:32: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df_regs.loc[i, 'year_coef'] = model_year.params[1]
C:\Users\user\AppData\Local\Temp\ipykernel_30904\3375503826.py:34: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df_regs.loc[i, 'year_pvalue'] = model_year.pvalues[1]
C:\Users\user\AppData\Local\Temp\ipykernel_30904\3375503826.py:14: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df_regs.loc[i, 'month_coef'] = model_month.params[1]
C:\Users\user\AppData\Local\Temp\ipykernel_30904\3375503826.py:16: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df_regs.loc[i, 'month_pvalue'] = model_month.pvalues[1]
C:\Users\user\AppData\Local\Temp\ipykernel_30904\3375503826.py:32: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df_regs.loc[i, 'year_coef'] = model_year.params[1]
C:\Users\user\AppData\Local\Temp\ipykernel_30904\3375503826.py:34: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df_regs.loc[i, 'year_pvalue'] = model_year.pvalues[1]
C:\Users\user\AppData\Local\Temp\ipykernel_30904\3375503826.py:14: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df_regs.loc[i, 'month_coef'] = model_month.params[1]
C:\Users\user\AppData\Local\Temp\ipykernel_30904\3375503826.py:16: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df_regs.loc[i, 'month_pvalue'] = model_month.pvalues[1]
C:\Users\user\AppData\Local\Temp\ipykernel_30904\3375503826.py:14: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df_regs.loc[i, 'month_coef'] = model_month.params[1]
C:\Users\user\AppData\Local\Temp\ipykernel_30904\3375503826.py:16: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df_regs.loc[i, 'month_pvalue'] = model_month.pvalues[1]
C:\Users\user\AppData\Local\Temp\ipykernel_30904\3375503826.py:32: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df_regs.loc[i, 'year_coef'] = model_year.params[1]
C:\Users\user\AppData\Local\Temp\ipykernel_30904\3375503826.py:34: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df_regs.loc[i, 'year_pvalue'] = model_year.pvalues[1]
C:\Users\user\AppData\Local\Temp\ipykernel_30904\3375503826.py:14: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df_regs.loc[i, 'month_coef'] = model_month.params[1]
C:\Users\user\AppData\Local\Temp\ipykernel_30904\3375503826.py:16: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df_regs.loc[i, 'month_pvalue'] = model_month.pvalues[1]
C:\Users\user\AppData\Local\Temp\ipykernel_30904\3375503826.py:14: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df_regs.loc[i, 'month_coef'] = model_month.params[1]
C:\Users\user\AppData\Local\Temp\ipykernel_30904\3375503826.py:16: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df_regs.loc[i, 'month_pvalue'] = model_month.pvalues[1]
C:\Users\user\AppData\Local\Temp\ipykernel_30904\3375503826.py:32: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df_regs.loc[i, 'year_coef'] = model_year.params[1]
C:\Users\user\AppData\Local\Temp\ipykernel_30904\3375503826.py:34: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df_regs.loc[i, 'year_pvalue'] = model_year.pvalues[1]
C:\Users\user\AppData\Local\Temp\ipykernel_30904\3375503826.py:14: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df_regs.loc[i, 'month_coef'] = model_month.params[1]
C:\Users\user\AppData\Local\Temp\ipykernel_30904\3375503826.py:16: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df_regs.loc[i, 'month_pvalue'] = model_month.pvalues[1]
C:\Users\user\AppData\Local\Temp\ipykernel_30904\3375503826.py:32: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df_regs.loc[i, 'year_coef'] = model_year.params[1]
C:\Users\user\AppData\Local\Temp\ipykernel_30904\3375503826.py:34: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df_regs.loc[i, 'year_pvalue'] = model_year.pvalues[1]
C:\Users\user\AppData\Local\Temp\ipykernel_30904\3375503826.py:14: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df_regs.loc[i, 'month_coef'] = model_month.params[1]
C:\Users\user\AppData\Local\Temp\ipykernel_30904\3375503826.py:16: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df_regs.loc[i, 'month_pvalue'] = model_month.pvalues[1]
C:\Users\user\AppData\Local\Temp\ipykernel_30904\3375503826.py:32: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df_regs.loc[i, 'year_coef'] = model_year.params[1]
C:\Users\user\AppData\Local\Temp\ipykernel_30904\3375503826.py:34: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df_regs.loc[i, 'year_pvalue'] = model_year.pvalues[1]
C:\Users\user\AppData\Local\Temp\ipykernel_30904\3375503826.py:14: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df_regs.loc[i, 'month_coef'] = model_month.params[1]
C:\Users\user\AppData\Local\Temp\ipykernel_30904\3375503826.py:16: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df_regs.loc[i, 'month_pvalue'] = model_month.pvalues[1]
C:\Users\user\AppData\Local\Temp\ipykernel_30904\3375503826.py:32: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df_regs.loc[i, 'year_coef'] = model_year.params[1]
C:\Users\user\AppData\Local\Temp\ipykernel_30904\3375503826.py:34: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df_regs.loc[i, 'year_pvalue'] = model_year.pvalues[1]
C:\Users\user\AppData\Local\Temp\ipykernel_30904\3375503826.py:14: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df_regs.loc[i, 'month_coef'] = model_month.params[1]
C:\Users\user\AppData\Local\Temp\ipykernel_30904\3375503826.py:16: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df_regs.loc[i, 'month_pvalue'] = model_month.pvalues[1]
C:\Users\user\AppData\Local\Temp\ipykernel_30904\3375503826.py:32: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df_regs.loc[i, 'year_coef'] = model_year.params[1]
C:\Users\user\AppData\Local\Temp\ipykernel_30904\3375503826.py:34: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df_regs.loc[i, 'year_pvalue'] = model_year.pvalues[1]
C:\Users\user\AppData\Local\Temp\ipykernel_30904\3375503826.py:14: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df_regs.loc[i, 'month_coef'] = model_month.params[1]
C:\Users\user\AppData\Local\Temp\ipykernel_30904\3375503826.py:16: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df_regs.loc[i, 'month_pvalue'] = model_month.pvalues[1]
C:\Users\user\AppData\Local\Temp\ipykernel_30904\3375503826.py:32: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df_regs.loc[i, 'year_coef'] = model_year.params[1]
C:\Users\user\AppData\Local\Temp\ipykernel_30904\3375503826.py:34: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df_regs.loc[i, 'year_pvalue'] = model_year.pvalues[1]
C:\Users\user\AppData\Local\Temp\ipykernel_30904\3375503826.py:14: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df_regs.loc[i, 'month_coef'] = model_month.params[1]
C:\Users\user\AppData\Local\Temp\ipykernel_30904\3375503826.py:16: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df_regs.loc[i, 'month_pvalue'] = model_month.pvalues[1]

In [66]:
yearly_page['만화'].isnull().sum()

1

In [75]:
df_regs

        month_coef month_score month_pvalue  year_coef year_score year_pvalue
건강/취미     0.628173    0.248938          0.0  21.766355   0.560771    0.002057
경제경영      0.052713    0.009524     0.192477   3.188734   0.349276    0.026038
과학        0.177088    0.054368     0.001632   7.523063   0.189576    0.119689
만화       -0.196832    0.047605     0.003257        NaN        NaN         NaN
사회과학      0.290675    0.128428     0.000001   3.494395    0.10022    0.270134
소설/시/희곡  -0.215155    0.117118     0.000003  -4.885736   0.111296    0.243754
수험서/자격증   0.034793    0.000244     0.834976        NaN        NaN         NaN
에세이      -0.267447    0.347183          0.0   -5.90735   0.675611     0.00031
여행       -1.021848    0.149819          0.0        NaN        NaN         NaN
역사       -0.692551    0.036063      0.01067 -37.086499   0.078973    0.330424
예술/대중문화   0.298662      0.0555     0.001454  14.858974   0.298427    0.043266
외국어       0.230144    0.108011     0.000007   1.524424   0.050671    0.439086
요리/살림    -0.031538    0.001361     0.622934  -6.953794    0.23816    0.076665
인문학       -0.27084    0.170584          0.0  -1.469237   0.032616    0.536671
자기계발      0.213946    0.386374          0.0   2.353128   0.344164    0.027436
종교/역학     0.549804    0.064935     0.000556   2.941674   0.059737    0.399719
좋은부모     -0.118513    0.033774      0.01353  -4.649982   0.148228    0.174036
참고서       4.186432    0.528872          0.0        NaN        NaN         NaN
청소년      -0.319937    0.020325     0.056243  -5.998563   0.238093    0.076712
컴퓨터/모바일   0.853539    0.095059     0.000025        NaN        NaN         NaN

In [72]:
print(df_regs.dropna().head(15).to_markdown())

|               |   month_coef |   month_score |   month_pvalue |   year_coef |   year_score |   year_pvalue |
|:--------------|-------------:|--------------:|---------------:|------------:|-------------:|--------------:|
| 건강/취미     |    0.628173  |    0.248938   |    1.01441e-12 |    21.7664  |    0.560771  |   0.00205673  |
| 경제경영      |    0.0527128 |    0.00952361 |    0.192477    |     3.18873 |    0.349276  |   0.0260381   |
| 과학          |    0.177088  |    0.0543683  |    0.00163244  |     7.52306 |    0.189576  |   0.119689    |
| 사회과학      |    0.290675  |    0.128428   |    7.82909e-07 |     3.49439 |    0.10022   |   0.270134    |
| 소설/시/희곡  |   -0.215155  |    0.117118   |    2.57366e-06 |    -4.88574 |    0.111296  |   0.243754    |
| 에세이        |   -0.267447  |    0.347183   |    3.29489e-18 |    -5.90735 |    0.675611  |   0.000309695 |
| 역사          |   -0.692551  |    0.0360626  |    0.01067     |   -37.0865  |    0.0789735 |   0.330424    |
| 예술/대중문화 |    0.298662  |    0.0555003  |    0.00145448  |    14.859   |    0.298427  |   0.0432659   |
| 외국어        |    0.230144  |    0.108011   |    6.65806e-06 |     1.52442 |    0.0506706 |   0.439086    |
| 요리/살림     |   -0.0315377 |    0.00136113 |    0.622934    |    -6.95379 |    0.23816   |   0.0766651   |
| 인문학        |   -0.27084   |    0.170584   |    8.3152e-09  |    -1.46924 |    0.0326163 |   0.536671    |
| 자기계발      |    0.213946  |    0.386374   |    1.26567e-20 |     2.35313 |    0.344164  |   0.0274362   |
| 종교/역학     |    0.549804  |    0.0649347  |    0.000556122 |     2.94167 |    0.0597369 |   0.399719    |
| 좋은부모      |   -0.118513  |    0.0337738  |    0.0135297   |    -4.64998 |    0.148228  |   0.174036    |
| 청소년        |   -0.319937  |    0.0203247  |    0.0562432   |    -5.99856 |    0.238093  |   0.0767122   |